# Generated by Django 6.0.3 on 2026-03-21 03:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0002_artical'),
    ]

    operations = [
        migrations.AlterField(
            model_name='artical',
            name='content',
            field=models.TextField(),
        ),
    ]
