# Generated by Django 6.0.3 on 2026-03-21 03:36

import tinymce.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0003_alter_artical_content'),
    ]

    operations = [
        migrations.AlterField(
            model_name='artical',
            name='content',
            field=tinymce.models.HTMLField(),
        ),
    ]
