# Generated by Django 6.0.3 on 2026-03-21 03:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0004_alter_artical_content'),
    ]

    operations = [
        migrations.AlterField(
            model_name='artical',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
