# Generated by Django 6.0.3 on 2026-03-25 16:07

import news.helpers
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0005_alter_artical_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='Feed',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('slug', models.SlugField(max_length=100, unique=True)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('published', 'Published')], default='draft', max_length=10)),
                ('ordering', models.IntegerField(default=0)),
                ('link', models.CharField(max_length=250)),
            ],
        ),
        migrations.AlterField(
            model_name='artical',
            name='image',
            field=models.ImageField(upload_to=news.helpers.get_file_path),
        ),
    ]
